src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rate;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\ManyToOne(targetEntity=Episode::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $episode;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(?int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->episode;
    }

    public function setEpisode(?Episode $episode): self
    {
        $this->episode = $episode;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProgramRepository::class)
 * @UniqueEntity(fields="title", message="ce titre existe déjà")
 * @ORM\Entity
 * @UniqueEntity("slug")
 */
class Program
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ne me laisse pas tout vide")
     * @Assert\Length(max="255", maxMessage="Le titre saisi {{ value }} est trop long, il ne devrait pas dépasser {{ limit }} caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Ne me laisse pas tout vide")
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="programs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="program")
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Actor::class, mappedBy="programs")
     */
    private $actors;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="programs")
     */
    private $owner;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setProgram($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use App\Entity\Program;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('summary', TextType::class)
            ->add('poster', TextType::class)
            // ->add('year', TextType::class)
            ->add('category', null, ['choice_label' => 'name'])
            ->add('actors', EntityType::class, ['class' => Actor::class, 'choice_label' => 'name', 'multiple' => true, 'expanded' => true,])
            ->add('actors', EntityType::class, [
                'class' => Actor::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Program;
use App\Entity\Season;
use App\Entity\Actor;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ProgramType;
use Doctrine\ORM\EntityManagerInterface;
use App\Service\Slugify;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

/**
 * @Route("/program", name="program_")
 */

class ProgramController extends AbstractController
{

    /**
     * Show all rows from Program's entity
     *
     * @Route("/", name="index")
     * @return Response A response instance
     */

    public function index(): Response
    {
        $programs = $this->getDoctrine()->getRepository(Program::class)->findAll();

        return $this->render('program/index.html.twig', [
            'programs' => $programs,
        ]);
    }

    /**
     * The controller for the program add form
     *
     * @Route("/new", name="new")
     */

    public function new(Request $request, Slugify $slugify, MailerInterface $mailer): Response
    {
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $slug = $slugify->generate($program->getTitle());
            $program->setSlug($slug);
            $entityManager->persist($program);
            $program->setOwner($this->getUser());
            $entityManager->flush();

            $email = (new Email())
                ->from($this->getParameter('mailer_from'))
                ->to('your_email@example.com')
                ->subject('Une nouvelle série vient d\'être publiée !')
                ->html($this->renderView('program/newProgramEmail.html.twig', ['program' => $program]));

            $mailer->send($email);

            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/new.html.twig', ["form" => $form->createView()]);
    }

    /**
     * Getting program by id
     *
     * @Route("/{slug}", name="show")
     * @return Response
     */

    public function show(Program $program): Response
    {
        return $this->render('program/show.html.twig', ['program' => $program]);
    }

    /**
     * Getting a season for a program by id
     *
     * @Route("/{slug}/seasons/{season<^[0-9]+$>}", name="season_show")
     * @return Response
     */

    public function showSeason(
        Program $program,
        Season $season
    ): Response {

        return $this->render(
            'program/season_show.html.twig',
            [
                'program' => $program,
                'season' => $season
            ]
        );
    }

    /**
     * Getting an actor by id
     *
     * @Route("/actor/{actor<^[0-9]+$>}", name="actor_show")
     * @return Response
     */

    public function showActor(Actor $actor): Response
    {

        return $this->render(
            'program/actor_show.html.twig',
            [
                'actor' => $actor
            ]
        );
    }

    /**
     * @Route("/{slug}/edit", name="edit", methods={"GET", "POST"})
     */

    public function edit(Request $request, Program $program, EntityManagerInterface $entityManager): Response
    {
        if (!($this->getUser() == $program->getOwner())) {
            throw new AccessDeniedException('Only the owner can edit the program!');
        }

        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('program_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('program/edit.html.twig', [
            'program' => $program,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{slug}/delete", name="delete", methods={"POST"})
     */
    public function delete(Request $request, Program $program, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $program->getId(), $request->request->get('_token'))) {
            $entityManager->remove($program);
            $entityManager->flush();
        }

        return $this->redirectToRoute('program_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/program/_delete_form.html.twig
<form method="post" action="{{ path('program_delete', {slug: program.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ program.id) }}">
    <button class="btn btn-secondary p-2 px-4">Delete</button>
</form>

templates/program/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-secondary p-2 px-4 mb-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/program/_navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
	<div class="container-fluid">

		<div class="navbarWild navbar-brand col col-lg-4">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<img src="{{ asset('build/images/carbon_logo-delicious.svg') }}" alt="logo" width="30" height="30">
			<a class="navbar-brand text-primary" href="/">Wild Séries</a>
		</div>

		<div class="collapse navbar-collapse col col-lg-4" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item dropdown">
					<a class="nav-link" href="/program" id="navbarDropdown" role="button">
						Programmes</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="/category" id="navbarDropdown" role="button">
						Catégories
					</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="/actor" id="navbarDropdown" role="button">
						Acteurs
					</a>
				</li>
				</li>
			</ul>
		</div>

		<div class="collapse navbar-collapse col col-lg-4" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link text-primary" href="/program/new/#/">Ajout programme</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-primary" href="/episode/new/">Ajout épisode</a>
				</li>
				<li class="nav-item">
					{% if app.user %}
					{{ app.user.email }}
					<a class="text-dark" href="{{ path('app_logout') }}">
						déconnexion</a>
					{% else %}
					<a class="text-dark" href="{{ path('login') }}">
						connexion</a>
					{% endif %}
				</li>
			</ul>
		</div>
	</div>

</nav>

templates/program/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Program{% endblock %}

{% block body %}
    <h1>Edit Program</h1>

    {{ include('program/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('program_index') }}">back to list</a>

    {{ include('program/_delete_form.html.twig') }}
{% endblock %}

templates/program/episode_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode
{{ episode.number }}
{% endblock %}

{% block body %}
<ul>
	<li>{{ episode.title }}</li>
	<li>Épisode
		{{ episode.number }}</li>
	<li>{{ episode.synopsis }}</li>
</ul>

{% if is_granted('ROLE_CONTRIBUTOR') %}
<div>
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button class="btn">{{ button_label|default('Save') }}</button>
	{{ form_end(form) }}
</div>
{% endif %}

{% if is_granted("ROLE_ADMIN") %}
<a href="{{ path('program_edit', { 'slug': program.slug} ) }}">Éditer</a>
{%endif%}

{% for comment in episode.comments %}
<div>
	<p class="fw-3">{{ comment.author.email }}</p>
	avis:
	{{ comment.comment }}
	- note:
	{{ comment.rate }}
	* - ({{ comment.date|date('Y/m/d H:i:s')}})

	{% if is_granted("ROLE_ADMIN") or app.user is same as(comment.author) %}
	{% include "/comment/_delete_form.html.twig" %}
	{% endif %}
</div>
{% endfor %}

<a href="{{ path('app_index') }}">Retour à l'accueil</a>
{% endblock %}

templates/program/index.html.twig
{% extends "base.html.twig" %}

{% block title %}All programs{% endblock %}

{% block body %}
<h1 class="text-center">Toutes les séries disponibles: </h1>
<main class="container">
    
    <div class=" mb-3">
        {% for program in programs %}
        <div class="row g-0 p-4">
            <div class="col-md-4">
                <img src="{{ program.poster }}" class="img-fluid rounded-start" alt="{{ program.title }}">
            </div>
            <div class="col-md-8 align-self-center">
                <div class="card-body">
                    <h2>{{ loop.index }} / {{ program.title }} - Catégorie : {{ program.category.name }}</h2>
                    <p>{{ program.summary }}</p>
                    <a href="{{ path('program_show', { slug: program.slug }) }}" class="btn btn-secondary p-2 px-4">
                        Voir le détail</a>
                </div>
            </div>           
        </div>
        {% else %}
        Aucune série trouvée.
        {% endfor %}
        <a href="{{ path('app_index') }}" class="btn btn-primary">Retour à l'accueil</a>
    </div>
</main>
{% endblock %}

templates/program/new.html.twig
{% extends "base.html.twig" %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}
<main class="container">
    <h1 class="text-center">Créer new programme</h1>
    <div class="form mb-3 text-dark">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-secondary p-2 px-4">Ajouter une série</button>
        {{ form_end(form) }}
    </div>
    <a class="btn btn-light p-2 px-4" href="{{ path('program_index') }}">Retour programmes</a>

</main>
{% endblock %}

templates/program/newProgramEmail.html.twig
{% extends "layout.html.twig" %}

{% block body %}
<main class="container">
    <row class="header">
            <h1 class="text-center">Bienvenue !</h1>
        </columns>
        <h1>{{ program.title }} </h1>
        <p>vient d'être publiée sur Wild Séries !</p>
        <p>Résumé: {{program.summary }}
    </row>
</main>
{% endblock %}

templates/program/season_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Saison #{{ season.number }}{% endblock %}

{% block body %}
<h1 class="mt-0 text-center">Liste des épisodes de la saison : {{ season.number }}</h1>

<main class="container">
    <img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
    <h2 class="mt-0">{{ program.title }}</h2>
    <p> La saison {{ season.number }} de la catégorie {{program.category.name }} a été lancé le {{ season.year}}
    </p>
    <p>{{ program.summary }} </p>
    <div class="row justify-content-center gap-5">
        
        {% for episode in season.episodes %}
        <div class="card bg-light mb-3 mb-5 p-0">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Episode : {{ episode.number }}</h3>
                    <a class="text-dark" href="{{ path('episode_show', { slug: episode.slug }) }}"> en savoir plus </a>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Titre : {{episode.title }}</h4>
                    <p>Resumé: {{episode.synopsis }}</p>
                </div>
            </div>
        </div>
        {% else %}
        Pas d'episode disponible.
        {% endfor %}
        <a class="text-dark" href="{{ path('program_index') }}">Retour à la liste des saisons</a>
    </div>
</main>
{% endblock %}

templates/program/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Série #{{ program.id }}
{% endblock %}

{% block body %}
	<main class="container">
		<div class=" mt-5">
			<div class="row g-0 p-4">
				<div class="col-md-4">
					<img class=" image align-self-start mr-3 mb-5 mt-5" src="{{ program.poster }}" alt="{{ program.title }} poster">
				</div>
				<div class="col-md-8 align-self-center">
					<div class="card-body">
						<h1 class="d-flex justify-content-center">{{ program.title }}</h1>
						<p class="d-flex justify-content-center">Catégorie :
							{{ program.category.name }}</p>
						<p>{{ program.summary }}</p>
					</div>
				</div>
				{% for season in program.seasons %}
					<div class="card-group" style="width: 20rem;">
						<h2 class="card-title fs-3">Saison
							{{ season.number }}
							- Année
							{{ season.year }}</h2>
						<p class="card-text">{{ season.description }}</p>
						<a class="btn text-light" href="{{ path('program_show',{ season: season.id, slug: program.slug  }) }}">Voir la fiche</a>
					</div>
					{% else %}
					Pas de saison disponible
				{% endfor %}
			</div>
		</div>
		<strong>Acteurs :</strong>
		<ul>
			{% for actor in program.actors %}
				<h3 href="{{ path('actor_show', { id: actor.id }) }}">{{ loop.index }} - {{ actor.name }}</h3>
			{% else %}
				<li>Aucun acteur pour cette série</li>
			{% endfor %}
		</ul>
		<a class="btn text-light mb-5" href="{{ path('program_index') }}">< Retour à la liste des programmes</a>
	</main>
{% endblock %}